/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author HP
 */
public class DataPelanggan extends javax.swing.JFrame {
        private Connection conn = new koneksi().connect() ;
        
         public void id_auto(){
        try{
            Connection c = new koneksi().connect();
            Statement stat = c.createStatement();
            String sql = "select max(right(id_pelanggan,4)) as no from datapelanggan";
            ResultSet rs = stat.executeQuery(sql);
            idpeng.setEnabled(false);
            while (rs.next()){
                if(rs.first()==false){
                    idpeng.setText("IDP001");
                }else {
                    rs.last();
                    int set_kode = rs.getInt(1)+1;
                    String no = String.valueOf(set_kode);
                    int kode_next = no.length();
                    for (int a = 0 ; a<4 - kode_next; a++){
                        no = "0"+no;
                        
                }
                    idpeng.setText("IDP"+no);
                }
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

        public void listed(){ 
        DefaultTableModel table = new DefaultTableModel(); 
        
        table.addColumn("ID Pelanggan");
        table.addColumn("Nama Pelanggan");  
        table.addColumn("No Telpon");  
        table.addColumn("Alamat"); 
    
 
        try{ 
            Connection kon = new koneksi().connect();
            String sql = "SELECT * FROM `datapelanggan`"; 
            Statement S = kon.createStatement(); 
            ResultSet rs = S.executeQuery(sql); 
             
            while(rs.next()){ 
                table.addRow(new Object[]{ 
                        rs.getString(1), 
                        rs.getString(2), 
                        rs.getString(3), 
                        rs.getString(4), 
                        


                        }); 
                } 
            tabeldatapenghuni.setModel(table); 
         }   
        catch(Exception e){ 
            System.out.println(e); 
        } 
    }

     public void clear(){ 
     
     idpeng.setText("");
     nmpeng.setText("");
     noidn.setText("");
     alamat.setText("");
     
     }
    /**
     * Creates new form pesanbarangmasuk
     */
    public DataPelanggan() {
        initComponents();
        listed();
        clear();
        id_auto();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodypanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        buttonkembali4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idpeng = new javax.swing.JTextField();
        nmpeng = new javax.swing.JTextField();
        noidn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldatapenghuni = new javax.swing.JTable();
        tf_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bodypanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        buttonkembali4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        buttonkembali4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Go Back_35px.png"))); // NOI18N
        buttonkembali4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonkembali4MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FORM Pelanggan");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarkontrakan/FormPenghuni_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addGap(198, 198, 198)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonkembali4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonkembali4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Nama PELANGGAN");

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("ID pelanggan");

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("no telpon");

        tabeldatapenghuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama Pelanggan", "No Telpon", "Alamat"
            }
        ));
        tabeldatapenghuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldatapenghuniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldatapenghuni);

        jButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnsimpan.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(153, 0, 0));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnubah.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        btnubah.setForeground(new java.awt.Color(153, 0, 0));
        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnrefresh.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(153, 0, 0));
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(153, 0, 0));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("alamat");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodypanelLayout.createSequentialGroup()
                        .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodypanelLayout.createSequentialGroup()
                                .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(39, 39, 39)
                                .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nmpeng, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idpeng, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(55, 55, 55))
                            .addGroup(bodypanelLayout.createSequentialGroup()
                                .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bodypanelLayout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(btnrefresh)
                                        .addGap(58, 58, 58)
                                        .addComponent(btnhapus))
                                    .addComponent(btnsimpan))
                                .addGap(45, 45, 45)))
                        .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noidn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bodypanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodypanelLayout.createSequentialGroup()
                        .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idpeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nmpeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bodypanelLayout.createSequentialGroup()
                        .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(noidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(alamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnubah)
                    .addComponent(btnrefresh)
                    .addComponent(btnhapus)
                    .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:

        //String tampilan = "d-M-yyy";
        //SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String idpelanggan  = idpeng.getText();
        String namapelanggan = nmpeng.getText();  
        String notelpon = noidn.getText();
        String alamat =  this.alamat.getText();
 
        if(idpelanggan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan ID Pelanggan");
        }
        else if(namapelanggan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Nama Pelanggan");
        }
        else if(notelpon.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan No Telpon");
        }
        else if(alamat.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Alamat");
        }else {
            try {
               String sql = "insert into datapelanggan values ('"+idpelanggan+"','"+namapelanggan+"','"+notelpon+"','"+alamat+"')";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql); 
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Input");
                clear();
                listed();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Input"+ e);
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
      //String tampilan = "d-M-yyy";
        //SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String idpelanggan = idpeng.getText();
        String namapelanggan = nmpeng.getText();  
        String notelpon = noidn.getText();
        String alamat =  this.alamat.getText();
 
        if(idpelanggan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan ID Pelanggan");
        }
        else if(namapelanggan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Nama Pelanggan");
        }
        else if(notelpon.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan No Telpon");
        }
        else if(alamat.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Alamat");
        }else {
            try {
               String sql = "update datapelanggan set nama_pelanggan=?, no_tlp=?, alamat=? where id_pelanggan=?"; 
            java.sql.PreparedStatement pst = conn.prepareStatement(sql); 
            pst.setString(1, namapelanggan);
            pst.setString(2, notelpon);
            pst.setString(3, alamat);
            pst.setString(4, idpelanggan);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Ubah");
                clear();
                listed();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Ubah "+ e);
            }
        }
        
    }//GEN-LAST:event_btnubahActionPerformed

    private void tabeldatapenghuniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldatapenghuniMouseClicked
        // TODO add your handling code here:
        int i = tabeldatapenghuni.getSelectedRow(); 
        if(i>-1){
          
            //btnPilihTanggal.setDate(tabeldatabarang.getValueAt(i, 0).parse());
            idpeng.setText(tabeldatapenghuni.getValueAt(i,0).toString()); 
            nmpeng.setText(tabeldatapenghuni.getValueAt(i,1).toString()); 
            noidn.setText(tabeldatapenghuni.getValueAt(i,2).toString());
            alamat.setText(tabeldatapenghuni.getValueAt(i,3).toString());
        }
    }//GEN-LAST:event_tabeldatapenghuniMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin ingin Hapus Data","Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);

        if(ok==0){
            String sql = "delete from datapelanggan where id_pelanggan ='"+idpeng.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement (sql);
                stat.executeUpdate();
                listed();
                clear();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Data Gagal DiHAPUS"+ e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        dispose(); 
        new DataPelanggan().setVisible(true);
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void buttonkembali4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonkembali4MouseClicked
        // TODO add your handling code here:
        dispose();
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_buttonkembali4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabel = new DefaultTableModel();

    tabel.addColumn("ID Pelanggan");
    tabel.addColumn("Nama Pelanggan");
    tabel.addColumn("No Telpon");
    tabel.addColumn("Alamat");

    try {
        Connection con = new koneksi().connect();
        String sql = "SELECT * FROM datapelanggan WHERE id_pelanggan LIKE ? OR nama_pelanggan LIKE ? OR no_tlp LIKE ? OR alamat LIKE ?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, "%" + tf_cari.getText() + "%");
        pst.setString(2, "%" + tf_cari.getText() + "%");
        pst.setString(3, "%" + tf_cari.getText() + "%");
        pst.setString(4, "%" + tf_cari.getText() + "%");

        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),

            });
        }
        tabeldatapenghuni.setModel(tabel);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JButton buttonkembali4;
    private javax.swing.JTextField idpeng;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nmpeng;
    private javax.swing.JTextField noidn;
    private javax.swing.JTable tabeldatapenghuni;
    private javax.swing.JTextField tf_cari;
    // End of variables declaration//GEN-END:variables
}
