/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author HP
 */
public class DataTagihan extends javax.swing.JFrame {
 public Connection conn = new koneksi().connect() ;
    /**
     * Creates new form DataTagihan
     *
     */
public void listed(){ 
        DefaultTableModel table = new DefaultTableModel(); 
        
        table.addColumn("ID Pelanggan");
        table.addColumn("Nama Pelanggan");  
        table.addColumn("No Telpon");  
        table.addColumn("Alamat"); 
        table.addColumn("ID Lapangan"); 
        table.addColumn("Tipe Lapangan");
        table.addColumn("No Lapangan");
        table.addColumn("Harga");
        table.addColumn("Jam");
        table.addColumn("Tanggal Masuk"); 
        table.addColumn("Status Pembayaran"); 
 
        try{ 
            Connection kon = new koneksi().connect();
            String sql = "SELECT * FROM datatagihan"; 
            Statement S = kon.createStatement(); 
            ResultSet rs = S.executeQuery(sql); 
             
            while(rs.next()){ 
                table.addRow(new Object[]{ 
                        rs.getString(1), 
                        rs.getString(2), 
                        rs.getString(3), 
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7),
                        rs.getString(8),
                        rs.getString(9),
                        rs.getString(10),
                        rs.getString(11),

                        }); 
                } 
            tabeldatatagihan.setModel(table); 
         }   
        catch(Exception e){ 
            System.out.println(e); 
        } 
    }

    public DataTagihan() {
    initComponents();
    listed();
    clear();
    nmpeng.setEnabled(false);
    nokon.setEnabled(false);
    hrg.setEnabled(false);
    noiden1.setEnabled(false);
    alamat.setEnabled(false);
    }
    
    public void isikode(String idpeng){
   txtidpeng.setText(idpeng);
    }
    
    public void isikd(String idkon){
   idkontr.setText(idkon);
    }
    
       
    public void clear(){ 
     txtidpeng.setText("");
     nmpeng.setText(""); 
     alamat.setText("");
     noiden1.setText("");
     idkontr.setText("");
     nokon.setText("");
     hrg.setText("");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodypanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtidpeng = new javax.swing.JTextField();
        nmpeng = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldatatagihan = new javax.swing.JTable();
        cr_br = new javax.swing.JTextField();
        cr = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        LP = new javax.swing.JButton();
        LK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idkontr = new javax.swing.JTextField();
        hrg = new javax.swing.JTextField();
        nokon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tipe = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        buttonkembali4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        noiden1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jxtTanggal = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jam = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bodypanel.setBackground(new java.awt.Color(255, 255, 255));
        bodypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Nama pelanggan");
        bodypanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("ID pelanggan");
        bodypanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Jam");
        bodypanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 20));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("No telpon");
        bodypanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        txtidpeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpengActionPerformed(evt);
            }
        });
        txtidpeng.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidpengKeyReleased(evt);
            }
        });
        bodypanel.add(txtidpeng, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, -1));
        bodypanel.add(nmpeng, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 130, -1));
        bodypanel.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 130, -1));

        tabeldatatagihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama Pelanggan", "No Telpon", "Alamat", "ID Lapangan", "Tipe Lapangan", "No Lapangan", "Harga", "Jam", "Tanggal Masuk", "Status Pembayaran"
            }
        ));
        tabeldatatagihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldatatagihanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldatatagihan);

        bodypanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 872, 160));
        bodypanel.add(cr_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 180, -1));

        cr.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        cr.setForeground(new java.awt.Color(153, 0, 0));
        cr.setText("Cari");
        cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crActionPerformed(evt);
            }
        });
        bodypanel.add(cr, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 74, -1));

        btnsimpan.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(153, 0, 0));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        bodypanel.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        btnubah.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        btnubah.setForeground(new java.awt.Color(153, 0, 0));
        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        bodypanel.add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 67, -1));

        btnrefresh.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(153, 0, 0));
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        bodypanel.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        btnhapus.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(153, 0, 0));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        bodypanel.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));

        LP.setFont(new java.awt.Font("Showcard Gothic", 0, 8)); // NOI18N
        LP.setForeground(new java.awt.Color(153, 0, 0));
        LP.setText("Lihat pelanggan");
        LP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPActionPerformed(evt);
            }
        });
        bodypanel.add(LP, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 140, 270, 30));

        LK.setFont(new java.awt.Font("Showcard Gothic", 0, 8)); // NOI18N
        LK.setForeground(new java.awt.Color(153, 0, 0));
        LK.setText("Lihat lapangan");
        LK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LKActionPerformed(evt);
            }
        });
        bodypanel.add(LK, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 280, 30));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("ID lapangan");
        bodypanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("No lapangan");
        bodypanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Harga");
        bodypanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        idkontr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idkontrActionPerformed(evt);
            }
        });
        idkontr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idkontrKeyReleased(evt);
            }
        });
        bodypanel.add(idkontr, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 130, -1));
        bodypanel.add(hrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 130, -1));
        bodypanel.add(nokon, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 130, -1));

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("Tipe lapangan");
        bodypanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        tipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A1", "A2", "A3" }));
        bodypanel.add(tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FORM TAGIHAN");

        buttonkembali4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        buttonkembali4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Go Back_35px.png"))); // NOI18N
        buttonkembali4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonkembali4MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarkontrakan/FormTagihan_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel12)
                .addGap(242, 242, 242)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(buttonkembali4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonkembali4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(32, 32, 32))
        );

        bodypanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        status.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Bayar", "Sudah Bayar" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        bodypanel.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setText("STATUS");
        bodypanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));
        bodypanel.add(noiden1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 130, -1));

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("alamat");
        bodypanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jxtTanggal.setDateFormatString("d-M-yyy");
        bodypanel.add(jxtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 130, -1));

        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("tanggal masuk");
        bodypanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, 20));

        jam.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10.00 - 11.00", "11.00 - 12.00", "12.00 - 13.00", "13.00 - 14.00", "14.00 - 15.00", "15.00 - 16.00", "16.00 - 17.00", "17.00 - 18.00", "18.00 - 19.00", "19.00 - 20.00", "20.00 - 21.00", "21.00 - 22.00", " " }));
        jam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamActionPerformed(evt);
            }
        });
        bodypanel.add(jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String tampilan = "d-MM-yyy";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(jxtTanggal.getDate()));
        String idpelanggan = txtidpeng.getText();
        String namapelanggan = nmpeng.getText();  
        String notelpon = noiden1.getText();
        String Alamat = alamat.getText();
        String idlapangan = idkontr.getText();
        String Tipe = tipe.getSelectedItem().toString();
        String nolapangan = nokon.getText();
        String harga = hrg.getText(); 
        String jam_main = jam.getSelectedItem().toString(); 
        String StatusPembayaran = status.getSelectedItem().toString();
        
        if(idpelanggan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan ID Pelanggan");
        }
        else if(namapelanggan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Nama Pelanggan");
        }
        else if(notelpon.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan No Telpon");
        }
        else if(Alamat.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Alamat");
        }
        else if(idlapangan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan ID Lapangan");
        }
        else if(Tipe.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Tipe Lapangan");
        }
        else if(nolapangan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan No Lapangan");
        } 
        else if (harga.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Masukan Harga");
        } 
        else if (jam_main.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Masukan Jam");
        }
        else if(tanggal.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Tanggal");
        } else if (StatusPembayaran.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Masukan Status Pembayaran");
        } else {
           
            try {
               String sql = "insert into datatagihan values ('"+idpelanggan+"','"+namapelanggan+"','"+notelpon+"','"+Alamat+"','"+idlapangan+"','"+Tipe+"','"+nolapangan+"','"+harga+"','"+jam_main+"','"+tanggal+"','"+StatusPembayaran+"')";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql); 
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Input");
                clear();
                listed();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Input"+ e);
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void tabeldatatagihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldatatagihanMouseClicked
        // TODO add your handling code here:
         int i = tabeldatatagihan.getSelectedRow(); 
        if(i>-1){
           
        try {
            Date date = new SimpleDateFormat("d-MM-yyy").parse((String)tabeldatatagihan.getValueAt(i,9));
              jxtTanggal.setDate(date);
            } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            //btnPilihTanggal.setDate(tabeldatabarang.getValueAt(i, 0).parse());
            txtidpeng.setText(tabeldatatagihan.getValueAt(i,0).toString()); 
            nmpeng.setText(tabeldatatagihan.getValueAt(i,1).toString());
            noiden1.setText(tabeldatatagihan.getValueAt(i,2).toString());
            alamat.setText(tabeldatatagihan.getValueAt(i,3).toString());
            idkontr.setText(tabeldatatagihan.getValueAt(i,4).toString());
            tipe.setSelectedItem(tabeldatatagihan.getValueAt(i,5).toString());
            nokon.setText(tabeldatatagihan.getValueAt(i,6).toString());
            hrg.setText(tabeldatatagihan.getValueAt(i,7).toString());
            jam.setSelectedItem(tabeldatatagihan.getValueAt(i,8).toString());
            status.setSelectedItem(tabeldatatagihan.getValueAt(i,10).toString());
        }
    }//GEN-LAST:event_tabeldatatagihanMouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        String tampilan = "d-MM-yyy";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(jxtTanggal.getDate()));
        String idpelanggan = txtidpeng.getText();
        String namapelanggan = nmpeng.getText();  
        String notelpon = noiden1.getText();
        String Alamat = alamat.getText();
        String idlapangan = idkontr.getText();
        String Tipe = tipe.getSelectedItem().toString();
        String nolapangan = nokon.getText();
        String harga = hrg.getText(); 
        String jam_main = jam.getSelectedItem().toString();
        String StatusPembayaran = status.getSelectedItem().toString();
 
        
        if(idpelanggan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan ID Pelanggan");
        }
        else if(namapelanggan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Nama Pelanggan");
        }
        else if(notelpon.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan No Telpon");
        }
        else if(Alamat.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Alamat");
        }
        else if(idlapangan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan ID Lapangan");
        }
        else if(Tipe.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Tipe Lapangan");
        } 
        
        else if(nolapangan.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan No Lapangan");
        } 
        else if(harga.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Harga");
        } 
        else if(harga.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Jam");
        } 
        else if(tanggal.isEmpty()) 
        { 
            JOptionPane.showMessageDialog(null, "Masukkan Tanggal");
        }
        else if (StatusPembayaran.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Masukan Status Pembayaran");
            
        } else {
            
            try {
               String sql = "update datatagihan set nama_pelanggan=?, no_tlp=?, alamat=?, id_lapangan=?, tipe_lapangan=?, no_lapangan=?, harga=?, jam=?, tanggal_masuk=?,  status=? where id_pelanggan=?";
                       //"insert into barang values ('"+kodebarang+"','"+namabarang+"','"+jenisbarang+"','"+stokbarang+"')";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql); 
            pst.setString(1, namapelanggan);
            pst.setString(2, notelpon);
            pst.setString(3, Alamat);
            pst.setString(4, idpelanggan);
            pst.setString(5, Tipe);
            pst.setString(6, nolapangan);
            pst.setString(7, harga);
            pst.setString(8, jam_main);
            pst.setString(9, tanggal);
            pst.setString(10, StatusPembayaran);
            pst.setString(11, idpelanggan);
            
            
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Edit");
                clear();
                listed();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Edit"+ e);
            }
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin ingin Hapus Data","Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);

        if(ok==0){
            String sql = "delete from datatagihan where id_pelanggan ='"+txtidpeng.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement (sql);
                stat.executeUpdate();
                listed();
                clear();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Data Gagal DiHAPUS"+ e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        dispose(); 
        new DataTagihan().setVisible(true);
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void LPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPActionPerformed
        // TODO add your handling code here:
        TabelPelanggan data = new TabelPelanggan();
        data.trans = this;
        data.setVisible(true);
        data.setResizable(false);
    }//GEN-LAST:event_LPActionPerformed

    private void txtidpengKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpengKeyReleased
        // TODO add your handling code here:

        try{
            Connection con = new koneksi().connect();
            String sql = "Select nama_pelanggan, no_tlp, alamat From datapelanggan where id_pelanggan = '"+ txtidpeng.getText()+ "'";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            
                while(rs.next()){
                nmpeng.setText(rs.getString("nama_pelanggan"));
                noiden1.setText(rs.getString("no_tlp"));
                alamat.setText(rs.getString("alamat"));
                System.out.println("masuk "+txtidpeng.getText()+"\np "+rs.getString("nama_pelanggan")+"\nni"+rs.getString("no_tlp"));            
                }
                
            
         }   
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtidpengKeyReleased

    private void idkontrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idkontrKeyReleased
        // TODO add your handling code here:
        try{
            Connection kon = new koneksi().connect();
            String sql = "Select tipe_lapangan, no_lapangan, harga From datalapangan where id_lapangan like '%"+ idkontr.getText()+ "%'";
            Statement S = kon.createStatement();
            ResultSet rs = S.executeQuery(sql);
            
            while(rs.next()){
                tipe.setSelectedItem(rs.getString("tipe_lapangan"));
                nokon.setText(rs.getString("no_lapangan"));
                hrg.setText(rs.getString("harga"));
                }
            
         }   
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_idkontrKeyReleased

    private void LKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LKActionPerformed
        // TODO add your handling code here:
        TabelLapangan data = new TabelLapangan();
        data.trans = this;
        data.setVisible(true);
        data.setResizable(false);
    }//GEN-LAST:event_LKActionPerformed

    private void buttonkembali4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonkembali4MouseClicked
        // TODO add your handling code here:
        dispose(); 
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_buttonkembali4MouseClicked

    private void crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabel = new DefaultTableModel();
        
        tabel.addColumn("Id Pelanggan");
        tabel.addColumn("Nama Pelanggan");
        tabel.addColumn("No Telpon");
        tabel.addColumn("Id Lapangan");
        tabel.addColumn("Tipe Lapangan");
        tabel.addColumn("No Lapangan");
        tabel.addColumn("Harga");
        tabel.addColumn("Jam");
        tabel.addColumn("Alamat");
        tabel.addColumn("Tanggal Masuk");
        tabel.addColumn("Status Pembayaran");
        try {
           Connection con = new koneksi().connect();
            String sql = "Select * From datatagihan where id_pelanggan like '%"+ cr_br.getText()+ "%' OR nama_pelanggan like '%"
                    + cr_br.getText()+"%' OR no_tlp like '%"+ cr_br.getText()+"%'"
                    + "OR id_lapangan like '%"+ cr_br.getText()+"%'"
                    + "OR tipe_lapangan like '%"+ cr_br.getText()+"%'"
                    + "OR no_lapangan like '%"+ cr_br.getText()+"%'"
                    + "OR harga like '%"+ cr_br.getText()+"%'"
                    + "OR jam like '%"+ cr_br.getText()+"%'"
                    + "OR alamat like '%"+ cr_br.getText()+"%'"
                    + "OR tanggal_masuk like '%"+ cr_br.getText()+"%'"
                    + "OR status like '%"+ cr_br.getText()+"%'";
            
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                tabel.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7),
                        rs.getString(8),
                        rs.getString(9),
                        rs.getString(10),
                        rs.getString(11),
                });
            }
            tabeldatatagihan.setModel(tabel);
       
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_crActionPerformed

    private void txtidpengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpengActionPerformed
        // TODO add your handling code here:
        
        try{
            Connection con = new koneksi().connect();
            String sql = "Select nama_pelanggan, no_tlp From datapelanggan where id_pelanggan like '%"+ txtidpeng.getText()+ "%'";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            
                while(rs.next()){
                nmpeng.setText(rs.getString("nama_pelanggan"));
                alamat.setText(rs.getString("no_tlp"));
                            
                }
            
         }   
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtidpengActionPerformed

    private void idkontrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idkontrActionPerformed
        // TODO add your handling code here:
        try (Connection kon = new koneksi().connect()) {
        String sql = "SELECT tipe_lapangan, no_lapangan, harga FROM datalapangan WHERE id_lapangan LIKE ?";
        PreparedStatement pstmt = kon.prepareStatement(sql);
        pstmt.setString(1, "%" + idkontr.getText() + "%");
        ResultSet rs = pstmt.executeQuery();

        while (rs.next()) {
            tipe.setSelectedItem(rs.getString("tipe_lapangan"));
            nokon.setText(rs.getString("no_lapangan"));
            hrg.setText(rs.getString("harga"));
        }
    } catch (Exception e) {
        System.out.println(e);
    }

    }//GEN-LAST:event_idkontrActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
        try{
            Connection kon = new koneksi().connect();
            String sql = "Select status From status where id_status like '%"+ status.getSelectedItem()+ "%'";
            Statement S = kon.createStatement();
            ResultSet rs = S.executeQuery(sql);
            
            while(rs.next()){
                status.setSelectedItem(rs.getString("status"));
                }
            
         }   
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_statusActionPerformed

    private void jamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataTagihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LK;
    private javax.swing.JButton LP;
    private javax.swing.JTextField alamat;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JButton buttonkembali4;
    private javax.swing.JButton cr;
    private javax.swing.JTextField cr_br;
    private javax.swing.JTextField hrg;
    private javax.swing.JTextField idkontr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jam;
    private com.toedter.calendar.JDateChooser jxtTanggal;
    private javax.swing.JTextField nmpeng;
    private javax.swing.JTextField noiden1;
    private javax.swing.JTextField nokon;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable tabeldatatagihan;
    private javax.swing.JComboBox<String> tipe;
    private javax.swing.JTextField txtidpeng;
    // End of variables declaration//GEN-END:variables
}
